//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class dich_vu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dich_vu()
        {
            this.dich_vu_phong = new HashSet<dich_vu_phong>();
        }
        [DisplayName("Mã dịch vụ")]
        public string ma_dich_vu { get; set; }
        [DisplayName("Tên dịch vụ")]
        public string ten_dich_vu { get; set; }
        [DisplayName("Giá dịch vụ")]
        public decimal gia_dich_vu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dich_vu_phong> dich_vu_phong { get; set; }
    }
}
