//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class phieu_dat_phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phieu_dat_phong()
        {
            this.thanh_toan = new HashSet<thanh_toan>();
        }
        [DisplayName("Mã phiếu đặt phòng")]
        public string ma_phieu_dat_phong { get; set; }
        [DisplayName("Ngày đặt phòng")]
        public System.DateTime ngay_dat { get; set; }
        [DisplayName("Ngày bắt đầu")]
        public System.DateTime ngay_bat_dau { get; set; }
        [DisplayName("Ngày kết thuac")]
        public System.DateTime ngay_ket_thuc { get; set; }
        [DisplayName("Tổng tiền")]
        public decimal tong_tien { get; set; }
        public string ma_phong { get; set; }
        public string ma_sv { get; set; }
    
        public virtual Phong Phong { get; set; }
        public virtual sinh_vien sinh_vien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thanh_toan> thanh_toan { get; set; }
    }
}
