//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class sinh_vien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sinh_vien()
        {
            this.phieu_dat_phong = new HashSet<phieu_dat_phong>();
        }
        [DisplayName("Mã sinh viên")]
        public string ma_sv { get; set; }
        [DisplayName("Họ và tên")]
        public string ho_ten { get; set; }
        [DisplayName("Giới tính")]
        public string gioi_tinh { get; set; }
        [DisplayName("Ảnh")]
        public string anh { get; set; }
        [DisplayName("Ngày sinh")]
        public System.DateTime ngay_sinh { get; set; }
        [DisplayName("Quê quán")]
        public string que_quan { get; set; }
        [DisplayName("Lớp")]
        public string lop { get; set; }
        [DisplayName("Số điện thoại")]
        public string sdt { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Ngày vào ở")]
        public System.DateTime ngay_vao_o { get; set; }
        public string ma_phong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieu_dat_phong> phieu_dat_phong { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
