//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.dich_vu_phong = new HashSet<dich_vu_phong>();
            this.phieu_dat_phong = new HashSet<phieu_dat_phong>();
            this.sinh_vien = new HashSet<sinh_vien>();
        }
        [DisplayName("Mã phòng")]
        public string ma_phong { get; set; }
        [DisplayName("Tên phòng")]
        public string ten_phong { get; set; }
        [DisplayName("Số giường")]
        public int so_giuong { get; set; }
        [DisplayName("Loại phòng")]
        public string loai_phong { get; set; }
        [DisplayName("Giá phòng")]
        public Nullable<decimal> gia_phong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dich_vu_phong> dich_vu_phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phieu_dat_phong> phieu_dat_phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sinh_vien> sinh_vien { get; set; }
    }
}
