//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qlktx_DAWEntities1 : DbContext
    {
        public qlktx_DAWEntities1()
            : base("name=qlktx_DAWEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dich_vu> dich_vu { get; set; }
        public virtual DbSet<dich_vu_phong> dich_vu_phong { get; set; }
        public virtual DbSet<phieu_dat_phong> phieu_dat_phong { get; set; }
        public virtual DbSet<Phong> Phong { get; set; }
        public virtual DbSet<quan_tri> quan_tri { get; set; }
        public virtual DbSet<sinh_vien> sinh_vien { get; set; }
        public virtual DbSet<thanh_toan> thanh_toan { get; set; }
    }
}
