//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class thanh_toan
    {
        [DisplayName("Mã thanh toán")]
        public string ma_thanh_toan { get; set; }
        [DisplayName("Ngày thanh toán")]
        public System.DateTime ngay_thanh_toan { get; set; }
        [DisplayName("Số tiền")]
        public decimal so_tien { get; set; }
        public string ma_phieu_dat_phong { get; set; }
    
        public virtual phieu_dat_phong phieu_dat_phong { get; set; }
    }
}
